fw=open('sample.txt','w')
fw.write('this is a sample text I am writing to this file\n')
fw.write('this is the second line\n')
fw.close()
fr=open('sample.txt','r')
print(fr.tell())
print(fr.readline())
print("hello")
print(fr.tell())
text=fr.read()
print(text)
print(fr.tell())

fr.close()